#spring 配置
spring:
#数据库连接 配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
#thymeleaf 配置
  thymeleaf:
# 在开发阶段建议关掉cache，否则可能出现页面更新问题
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html
  resources:
#  静态文件位置  使用thymeleaf模板时 默认为static
#  SpringSession 改 redis 官方示例 https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot-redis.html 用keys * 检测是否成功
    static-locations: classpath:/static/
  http:
    multipart:
  redis:
    host: localhost
    port: 6379
    password:
  session:
    store-type: redis
    redis:
      namespace: blog

#   mybatis 配置
mybatis:
    typeAliasesPackage: com.echo.project
    # 由于mybatis的xml文件 跟mapper不在同一个文件夹，设置扫描路径
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml

# spring-boot-tomcat 配置
server:
  port: 3639
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout:
shiro:
  user:
        loginUrl: /login

#pagehelper 配置   参照github官方示例
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

eureka:
  client:
    registerWithEureka: false  #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: false       #为true时，可以启动，但报异常：Cannot execute request on any known server


