#spring 配置
spring:
#数据库连接 配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
#thymeleaf 配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html
  resources:
    static-locations: classpath:/static/
# 由于mybatis的xml文件 跟mapper不在同一个文件夹，设置扫描配置
mybatis:
    typeAliasesPackage: com.echo.project
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml
# 默认端口设置为8088
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
shiro:
  user:
        loginUrl: /login




